# Configuration file for obesity prediction model training

# Global settings
data_path: "data/preprocessed"
log_level: "INFO"
random_state: 42

# Training configuration
training:
  model_path: "models"
  
  # Feature selection
  features:
    names: [
      "Weight", "Height", "FCVC", "NCP", "CH2O", "FAF", "TUE", "CAEC", "CALC",
      "family_history_with_overweight", "FAVC", "SMOKE", "SCC",
      "Gender_Male", "MTRANS_Bike", "MTRANS_Motorbike", "MTRANS_Public_Transportation",
      "MTRANS_Walking", "Age_Category_Adult", "Age_Category_Senior", "Age_Category_Young Adult"
    ]
  
  # Optuna hyperparameter optimization
  optuna:
    n_trials: 20
  
  # GPU settings
  gpu:
    enabled: false
    id: 0
    platform_id: 0
  
  # LightGBM hyperparameters
  lightgbm:
    verbosity: -1
    objective: "multiclass"
    num_class: 7
    
    # Hyperparameters to optimize
    n_estimators:
      enabled: true
      type: "int"
      minimum: 100
      maximum: 1000
      step: 50
      
    max_depth:
      enabled: true
      type: "int"
      minimum: 3
      maximum: 15
      step: 1
      
    learning_rate:
      enabled: true
      type: "float"
      minimum: 0.01
      maximum: 0.3
      step: 0.01
      
    num_leaves:
      enabled: true
      type: "int"
      minimum: 10
      maximum: 300
      step: 10
      
    min_child_samples:
      enabled: true
      type: "int"
      minimum: 5
      maximum: 100
      step: 5
      
    subsample:
      enabled: true
      type: "float"
      minimum: 0.6
      maximum: 1.0
      step: 0.1
      
    colsample_bytree:
      enabled: true
      type: "float"
      minimum: 0.6
      maximum: 1.0
      step: 0.1
      
    reg_alpha:
      enabled: true
      type: "float"
      minimum: 0.0
      maximum: 10.0
      step: 0.1
      
    reg_lambda:
      enabled: true
      type: "float"
      minimum: 0.0
      maximum: 10.0
      step: 0.1