name: dsi-ml6-env
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - lightgbm
    - optuna
    - scikit-learn
    - pandas
    - numpy
    - pyyaml
    - joblib
    - streamlit
    - plotly
    - matplotlib
    - seaborn
    - SQLAlchemy
    - shap
    - aquarel
    - ipython